language: cpp
dist: xenial

notifications:
  email:
    recipients:
      - git@bensokol.com
    on_success: change # default: always
    on_failure: always # default: always

matrix:
  include:

    # cppcheck
    - os: linux
      sudo: true
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libpcre3
            - libpcre3-dev
      before_script:
        - wget https://github.com/danmar/cppcheck/archive/1.87.tar.gz -O /tmp/cppcheck.tar.gz
        - tar -xvf /tmp/cppcheck.tar.gz
        - pushd cppcheck-1.87 && make SRCDIR=build CFGDIR=cfg HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-reorder -Wno-sign-compare -Wno-unused-function" && sudo make install SRCDIR=build CFGDIR=cfg HAVE_RULES=yes CXXFLAGS="-O2 -DNDEBUG -Wall -Wno-reorder -Wno-sign-compare -Wno-unused-function"&& popd
        - export PATH=$PATH:$PWD/cppcheck-1.87:$PWD/cppcheck-1.87/cfg
      script:
        - make var
        - make cppcheck

    # g++ 5
    - os: linux
      compiler: gcc

    # g++ 8
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # XCode 10.1
    - os: osx
      osx_image: xcode10.1

    # macOS using GCC-8
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew update && brew install gcc && brew link gcc && CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make var
  - make
  - make run
