language: cpp
dist: xenial

notifications:
  email:
    recipients:
      - git@bensokol.com
    on_success: change # default: always
    on_failure: always # default: always

matrix:
  include:

    # cppcheck
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cppcheck
      env:
        - MATRIX_EVAL=""
      script:
        - make var
        - make cppcheck

    # g++ 5
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL=""

    # g++ 8
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # XCode 10.1
    - os: osx
      osx_image: xcode10.1

    # macOS using GCC-8
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew update && brew install gcc && brew link gcc && CC=gcc-8 && CXX=g++-8"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make var
  - make -j
  - make run
