language: cpp
dist: xenial
sudo: required

matrix:
  include:

    # CppCheck
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      script:
        - make
        - make var
        - make cppcheck

    # g++ 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      script:
        - make
        - make var
        - make run

    # g++ 6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      script:
        - make
        - make var
        - make run

    # g++ 7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      script:
        - make
        - make var
        - make run

    # XCode 10.1
    - os: osx
      osx_image: xcode10.1
      script:
        - make
        - make var
        - make run
